# Generated by Django 3.1 on 2020-08-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        # Oscar apps
        ('catalogue', '0001_initial'),
        ('partner', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
    ]
